//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ctp_rgres.ws_exchange_form {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExchangeDataDevelopmentsFormSoapBinding", Namespace="uri:faulty-knowledge-equipment")]
    public partial class ExchangeDataDevelopmentsForm : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExchangeDataDevelopmentsForm() {
            this.Url = "http://10.20.18.92/dev_defect/ws/ws_exchange_form_develop.1cws";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setCompletedEventHandler setCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("uri:faulty-knowledge-equipment#ExchangeDataDevelopmentsForm:set", RequestNamespace="uri:faulty-knowledge-equipment", ResponseNamespace="uri:faulty-knowledge-equipment", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public WA_RETURN[] set(im_data im_data) {
            object[] results = this.Invoke("set", new object[] {
                        im_data});
            return ((WA_RETURN[])(results[0]));
        }
        
        /// <remarks/>
        public void setAsync(im_data im_data) {
            this.setAsync(im_data, null);
        }
        
        /// <remarks/>
        public void setAsync(im_data im_data, object userState) {
            if ((this.setOperationCompleted == null)) {
                this.setOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetOperationCompleted);
            }
            this.InvokeAsync("set", new object[] {
                        im_data}, this.setOperationCompleted, userState);
        }
        
        private void OnsetOperationCompleted(object arg) {
            if ((this.setCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setCompleted(this, new setCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:faulty-knowledge-equipment")]
    public partial class im_data {
        
        private string dIRECTField;
        
        private string uID_HANDLERField;
        
        private string dATA_CREATEField;
        
        private string wOKRSField;
        
        private string dEPATMENTField;
        
        private string uIDField;
        
        private WA_RUN[] rUNField;
        
        /// <remarks/>
        public string DIRECT {
            get {
                return this.dIRECTField;
            }
            set {
                this.dIRECTField = value;
            }
        }
        
        /// <remarks/>
        public string UID_HANDLER {
            get {
                return this.uID_HANDLERField;
            }
            set {
                this.uID_HANDLERField = value;
            }
        }
        
        /// <remarks/>
        public string DATA_CREATE {
            get {
                return this.dATA_CREATEField;
            }
            set {
                this.dATA_CREATEField = value;
            }
        }
        
        /// <remarks/>
        public string WOKRS {
            get {
                return this.wOKRSField;
            }
            set {
                this.wOKRSField = value;
            }
        }
        
        /// <remarks/>
        public string DEPATMENT {
            get {
                return this.dEPATMENTField;
            }
            set {
                this.dEPATMENTField = value;
            }
        }
        
        /// <remarks/>
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RUN")]
        public WA_RUN[] RUN {
            get {
                return this.rUNField;
            }
            set {
                this.rUNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:faulty-knowledge-equipment")]
    public partial class WA_RUN {
        
        private string nUMBERField;
        
        private WA_TM[] tmField;
        
        /// <remarks/>
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TM")]
        public WA_TM[] TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:faulty-knowledge-equipment")]
    public partial class WA_TM {
        
        private string tM_NAMEField;
        
        private string tM_DATE_BEGINField;
        
        private string tM_TIME_BEGINField;
        
        private string tM_DATE_ENDField;
        
        private string tM_TIME_ENDField;
        
        /// <remarks/>
        public string TM_NAME {
            get {
                return this.tM_NAMEField;
            }
            set {
                this.tM_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string TM_DATE_BEGIN {
            get {
                return this.tM_DATE_BEGINField;
            }
            set {
                this.tM_DATE_BEGINField = value;
            }
        }
        
        /// <remarks/>
        public string TM_TIME_BEGIN {
            get {
                return this.tM_TIME_BEGINField;
            }
            set {
                this.tM_TIME_BEGINField = value;
            }
        }
        
        /// <remarks/>
        public string TM_DATE_END {
            get {
                return this.tM_DATE_ENDField;
            }
            set {
                this.tM_DATE_ENDField = value;
            }
        }
        
        /// <remarks/>
        public string TM_TIME_END {
            get {
                return this.tM_TIME_ENDField;
            }
            set {
                this.tM_TIME_ENDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:faulty-knowledge-equipment")]
    public partial class WA_RETURN {
        
        private string sTATUSField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setCompletedEventHandler(object sender, setCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WA_RETURN[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WA_RETURN[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591